# Generic
max_email_count: 100
rules_file: "conf/rules.json"

# Google specific
google:
  token_file: "conf/token.json"
  credential_file: "conf/credentials.json"
  redirect_port: 53669
  scopes:
    - https://www.googleapis.com/auth/gmail.modify

# data
database:
  db_name: postgres
  table_name: emails
  host: 127.0.0.1
  port: 5432
  user: postgres